apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: helloWorldTask
  annotations:
    alauda.io/displayName.zh-CN: "Hello world"
    alauda.io/version: "0.0.2"
  labels:
    category: CI
spec:
  engine: gotpl
  agent:
    label: "temp"
  body: |+
    echo "{{.helloText}}"
  arguments:
    - name: "helloText"
      schema:
        type: string
      required: true
      display:
        type: string
        name:
          zh-CN: "Hello text"
          en: "Hello text"
        description:
          zh-CN: "Hello text"
          en: "Hello text"